version: '3'

services:
  backend:
    build:
      context: ./server
      dockerfile: ./Dockerfile
    image: 'tarcea/jokes-backend'
    ports:
      - '3001:3001'
  frontend:
    build:
      context: ./client
      dockerfile: ./Dockerfile
    image: 'tarcea/jokes-frontend'
    ports:
      - '3000:3000'
